version: 2

#sources:
#  - name: raw
#    tables:
#      - name: dbt.raw_jobs

models:
  - name: stg_jobs
    columns:
      - name: job_link
        tests:
          - unique
          - not_null
      - name: company
        tests:
          - not_null
      - name: job_title
        tests:
          - unique_job_title_per_company:
              column_name_2: company
      - name: job_level
        tests:
          - valid_job_level